---
kind: ConfigMap
apiVersion: v1
metadata:
  name: silent-auction-frontend
  annotations:
    argocd.argoproj.io/sync-wave: "1"
immutable: false
data:
  BACKEND_URL: 'http://silent-auction-backend:6443/api/v1'
  KEYCLOAK_CLIENT_ID: 'frontend'
  KEYCLOAK_REALM: 'silent-auction'
  KEYCLOAK_URL: 'https://sso.bastion.blueguardian.co'
  MAX_TABLE_NUMBER: '20'
  MIN_TABLE_NUMBER: '1'
