---
kind: ConfigMap
apiVersion: v1
metadata:
  name: silent-auction-frontend
  annotations:
    argocd.argoproj.io/sync-wave: "1"
immutable: false
data:
  .env: |
    KEYCLOAK_CLIENT_ID=frontend
    KEYCLOAK_REALM=silent-auction
    KEYCLOAK_URL=http://localhost:8000
    BACKEND_URL=http://localhost:6443/api/v1
    MIN_TABLE_NUMBER=1
    MAX_TABLE_NUMBER=20
