apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-sql
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  init.sql: |
    \c silent-auction
    CREATE SCHEMA IF NOT EXISTS auction;
immutable: false