---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: silent-auction-frontend
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"silent-auction-backend"}]'
  labels:
    app.kubernetes.io/instance: silent-auction
    app.kubernetes.io/part-of: silent-auction
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: silent-auction-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: silent-auction-frontend
        app.kubernetes.io/part-of: silent-auction
        app: silent-auction
        version: "1"
        sidecar.istio.io/inject: 'true'
      annotations:
        app.openshift.io/connects-to: silent-auction-backend
    spec:
      serviceAccountName: silent-auction
      containers:
        - name: silent-auction-frontend
          image: 'quay.io/ahussey/silent-auction/frontend:latest'
          securityContext:
            runAsUser: 10001
          resources:
            limits:
              cpu: '1'
              memory: 4Gi
            requests:
              cpu: '1'
              memory: 256Mi
          env:
            - name: KEYCLOAK_URL
              value: https://sso.bastion.blueguardian.co
            - name: BACKEND_URL
              value: http://silent-auction-backend:6443/api/v1
            - name: MIN_TABLE_NUMBER
              value: '1'
            - name: MAX_TABLE_NUMBER
              value: '20'
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 1
  progressDeadlineSeconds: 600
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: silent-auction-backend
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app.kubernetes.io/instance: silent-auction
    app.kubernetes.io/part-of: silent-auction
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: silent-auction-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: silent-auction-backend
        app.kubernetes.io/instance: silent-auction-backend
        app.kubernetes.io/part-of: silent-auction
        app: silent-auction
        version: "3"
        sidecar.istio.io/inject: 'true'
    spec:
      serviceAccountName: silent-auction
      containers:
        - name: silent-auction-backend
          image: 'quay.io/ahussey/silent-auction/backend:latest'
          securityContext:
            runAsUser: 10001
          resources:
            limits:
              cpu: '1'
              memory: 4Gi
            requests:
              cpu: '1'
              memory: 256Mi
          ports:
            - name: http
              containerPort: 6443
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 1
  progressDeadlineSeconds: 600
