---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: silent-auction-frontend
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"silent-auction-backend"}]'
  labels:
    app.kubernetes.io/instance: silent-auction
    app.kubernetes.io/part-of: silent-auction
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: silent-auction-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: silent-auction-frontend
        app.kubernetes.io/part-of: silent-auction
        app: silent-auction
        version: "2"
        sidecar.istio.io/inject: 'true'
      annotations:
        app.openshift.io/connects-to: silent-auction-backend
    spec:
      serviceAccountName: silent-auction
      containers:
        - name: silent-auction-frontend
          image: 'quay.io/ahussey/silent-auction/frontend:latest'
          securityContext:
            runAsUser: 10001
          resources:
            limits:
              cpu: '1'
              memory: 4Gi
            requests:
              cpu: '1'
              memory: 256Mi
          env:
            - name: KEYCLOAK_URL
              valueFrom:
                configMapKeyRef:
                  name: silent-auction-frontend
                  key: KEYCLOAK_URL
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: silent-auction-frontend
                  key: KEYCLOAK_CLIENT_ID
            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: silent-auction-frontend
                  key: KEYCLOAK_REALM
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: silent-auction-frontend
                  key: BACKEND_URL
            - name: MIN_TABLE_NUMBER
              valueFrom:
                configMapKeyRef:
                  name: silent-auction-frontend
                  key: MIN_TABLE_NUMBER
            - name: MAX_TABLE_NUMBER
              valueFrom:
                configMapKeyRef:
                  name: silent-auction-frontend
                  key: MAX_TABLE_NUMBER
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 1
  progressDeadlineSeconds: 600
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: silent-auction-backend
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app.kubernetes.io/instance: silent-auction
    app.kubernetes.io/part-of: silent-auction
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: silent-auction-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: silent-auction-backend
        app.kubernetes.io/instance: silent-auction-backend
        app.kubernetes.io/part-of: silent-auction
        app: silent-auction
        version: "3"
        sidecar.istio.io/inject: 'true'
    spec:
      serviceAccountName: silent-auction
      containers:
        - name: silent-auction-backend
          image: 'quay.io/ahussey/silent-auction/backend:latest'
          securityContext:
            runAsUser: 10001
          resources:
            limits:
              cpu: '1'
              memory: 4Gi
            requests:
              cpu: '1'
              memory: 256Mi
          ports:
            - name: http
              containerPort: 6443
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 1
  progressDeadlineSeconds: 600
