kind: Deployment
apiVersion: apps/v1
metadata:
  name: silent-auction-demo-frontend
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: silent-auction-demo-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: silent-auction-demo-frontend
    spec:
      containers:
        - name: silent-auction-demo-frontend
          image: 'quay.io/ahussey/silent-auction/frontend:latest'
          securityContext:
            runAsUser: 10001
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 1
              memory: 256Mi
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
