---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
  - crunchy-instance.yaml
  - db-init-sql.yaml
  - pgadmin.yaml
  - deployment.yaml
  - routes.yaml
  - secrets.yaml
images:
  - name: quay.io/ahussey/silent-auction/frontend
    digest: sha256:0c12198521783b2f0cf244c3782b07193fa589de61e8071909e669d9ce3cce17