---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
  - crunchy-instance.yaml
  - db-init-sql.yaml
  - pgadmin.yaml
  - service-account.yaml
  - services.yaml
  - secrets.yaml
  - configmaps.yaml
  - rollouts.yaml
images:
  - name: quay.io/ahussey/silent-auction/frontend
    digest: sha256:3d5f1b19d7d354468c91ec6c758cb23166cea8e1f1900e14a258726382d1c828
  - name: quay.io/ahussey/silent-auction/backend
    digest: sha256:999c4154e000c5265b4e12c38dd7c292dcd0a56cab5352fa08967c68da37b418
