---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
  - crunchy-instance.yaml
  - db-init-sql.yaml
  - pgadmin.yaml
  - service-account.yaml
  - services.yaml
  - secrets.yaml
  - configmaps.yaml
  - rollouts.yaml
  - tkn-pac-repos.yaml
images:
  - name: quay.io/ahussey/silent-auction/frontend
    digest: sha256:85a7fd77c30d9606dd7acdf9bb02d5c3b3e78b069c4d5c382cad6a57adcfd31c
  - name: quay.io/ahussey/silent-auction/backend
    digest: sha256:e341760b9562a996a9b0eba20ddfed080619aac7af41a32a7dfe46c3f12dc1f7
