---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
  - crunchy-instance.yaml
  - db-init-sql.yaml
  - pgadmin.yaml
  - service-account.yaml
  - services.yaml
  - secrets.yaml
  - configmaps.yaml
  - rollouts.yaml
images:
  - name: quay.io/ahussey/silent-auction/frontend
    digest: sha256:dd1d3c8cc32d76f29853ea6fdbbdd580768000ebd4d9112997bf39fc48936b8d
  - name: quay.io/ahussey/silent-auction/backend
    digest: sha256:d5636804e046705e4afbd01866463b7ce172a03063f6436cfe348689fc329e75
