---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
  - crunchy-instance.yaml
  - db-init-sql.yaml
  - pgadmin.yaml
  - service-account.yaml
  - services.yaml
  - secrets.yaml
  - configmaps.yaml
  - rollouts.yaml
  - tkn-pac-repos.yaml
images:
  - name: quay.io/ahussey/silent-auction/frontend
    digest: sha256:a6c8d593aab6f4427edf953ce28d70ec0a86c29dc8e05d0b72582672cd9329e0
  - name: quay.io/ahussey/silent-auction/backend
    digest: sha256:c39cb432cae4cc926cfe0fc55ce193beb99ee9bc50702f402f191b0c054d99ca
