---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
  - crunchy-instance.yaml
  - db-init-sql.yaml
  - pgadmin.yaml
  - service-account.yaml
  - deployment.yaml
  - routes.yaml
  - secrets.yaml
images:
  - name: quay.io/ahussey/silent-auction/frontend
    digest: sha256:8ee4916aef89cc8e26901126637702ae4b4cfc694c8f6e43995028a9fc5e60cb
