---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
  - crunchy-instance.yaml
  - db-init-sql.yaml
  - pgadmin.yaml
  - service-account.yaml
  - deployment.yaml
  - services.yaml
  - secrets.yaml
  - configmaps.yaml
  - rollouts.yaml
images:
  - name: quay.io/ahussey/silent-auction/frontend
    digest: sha256:107d7ee73cdd362849160f2865186e2ba43a72317021072d68cea6af60dba208
  - name: quay.io/ahussey/silent-auction/backend
    digest: sha256:07d9b771cfbfff6f86f9d1c2f174efe23e9b500df98db14a1b5d11b304aaf18d
