---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PGAdmin
metadata:
  name: pgadmin
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  metadata:
    labels:
      sidecar.istio.io/inject: 'false'
      app: pgadmin
      version: "1"
  dataVolumeClaimSpec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  serverGroups:
    - name: silent-auction
      postgresClusterSelector:
        matchLabels:
          app: silent-auction
  config:
    settings:
      DEFAULT_SERVER: '0.0.0.0'
  users:
    - username: admin@pgo.io
      role: Administrator
      passwordRef:
        name: silent-auction-pguser-silent-auction
        key: password
