---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: silent-auction-frontend
  namespace: production
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"silent-auction-backend"}]'
  labels:
    app.kubernetes.io/instance: silent-auction
    app.kubernetes.io/part-of: silent-auction
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: silent-auction-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: silent-auction-frontend
        app.kubernetes.io/part-of: silent-auction
        app: silent-auction
        version: "17"
        sidecar.istio.io/inject: 'true'
      annotations:
        app.openshift.io/connects-to: silent-auction-backend
    spec:
      serviceAccountName: silent-auction
      volumes:
        - name: modernjs-env
          configMap:
            name: silent-auction-frontend
      containers:
        - name: silent-auction-frontend
          image: 'quay.io/ahussey/silent-auction/frontend:latest'
          securityContext:
            runAsUser: 10001
          resources:
            limits:
              cpu: '0.5'
              memory: 4Gi
            requests:
              cpu: '0.1'
              memory: 256Mi
          volumeMounts:
            - name: modernjs-env
              mountPath: /opt/app-root/src/.env
              subPath: .env
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    canary:
      minPodsPerReplicaSet: 1
      stableService: silent-auction-frontend-stable
      canaryService: silent-auction-frontend-canary
      scaleDownDelaySeconds: 60
      trafficRouting:
        istio:
          virtualService:
            name: silent-auction-frontend
            routes:
              - silent-auction-frontend
      steps:
        - setWeight: 5
        - pause:
            duration: 10m
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: silent-auction-backend
  namespace: production
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app.kubernetes.io/instance: silent-auction
    app.kubernetes.io/part-of: silent-auction
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: silent-auction-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: silent-auction-backend
        app.kubernetes.io/instance: silent-auction-backend
        app.kubernetes.io/part-of: silent-auction
        app: silent-auction
        version: "16"
        sidecar.istio.io/inject: 'true'
    spec:
      serviceAccountName: silent-auction
      containers:
        - name: silent-auction-backend
          image: 'quay.io/ahussey/silent-auction/backend:latest'
          securityContext:
            runAsUser: 10001
          resources:
            limits:
              cpu: '0.5'
              memory: 4Gi
            requests:
              cpu: '0.1'
              memory: 256Mi
          ports:
            - name: http
              containerPort: 6443
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    canary:
      minPodsPerReplicaSet: 1
      canaryService: silent-auction-backend-canary
      stableService: silent-auction-backend-stable
      scaleDownDelaySeconds: 60
      trafficRouting:
        istio:
          virtualService:
            name: silent-auction-backend
            routes:
              - silent-auction-backend
      steps:
        - setWeight: 5
        - pause:
            duration: 10m
