---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    postgres-operator.crunchydata.com/pgadmin: pgadmin
  ports:
    - name: pgadmin
      protocol: TCP
      port: 5050
      targetPort: pgadmin
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: pgadmin
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  to:
    kind: Service
    name: pgadmin
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  subdomain: pgadmin-production
  path: /
  port:
    targetPort: pgadmin
---
apiVersion: v1
kind: Service
metadata:
  name: silent-auction-frontend
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app.kubernetes.io/name: silent-auction-frontend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: silent-auction-frontend
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  to:
    kind: Service
    name: silent-auction-frontend
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  subdomain: silent-auction
  path: /
  port:
    targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: silent-auction-backend
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app.kubernetes.io/name: silent-auction-backend
  ports:
    - name: http
      protocol: TCP
      port: 6443
      targetPort: 6443
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: silent-auction-backend
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  to:
    kind: Service
    name: silent-auction-backend
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  subdomain: silent-auction-backend
  path: /
  port:
    targetPort: http