---
apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: ahussey-redhat-silent-auction-frontend
  namespace: build
spec:
  url: 'https://github.com/ahussey-redhat/silent-auction-frontend'
---
apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: ahussey-redhat-silent-auction-backend
  namespace: build
spec:
  url: 'https://github.com/ahussey-redhat/silent-auction-backend'
