---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'v5'
    target:
      kind: Subscription
      name: crunchy-postgres-operator
