---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: github-oauth-config
  namespace: openshift-devspaces
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    che.eclipse.org/oauth-scm-server: github
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
spec:
  itemPath: "vaults/Red Hat/items/GitHub - Dev Spaces OAuth"
