commonLabels: {}
connect:
  create: true
  replicas: 1
  api:
    name: onepassword-connect-api
    imageRepository: docker.io/1password/connect-api
    resources: {}
    httpPort: 8080
    httpsPort: 8443
    logLevel: info
    serviceMonitor:
      enabled: true
      interval: 30s
      path: "/metrics"
      params: {}
      annotations: {}
  sync:
    name: onepassword-connect-sync
    imageRepository: docker.io/1password/connect-sync
    resources: {}
    httpPort: 8081
    logLevel: info
  applicationName: onepassword-connect
  host: onepassword-connect
  serviceType: NodePort
  serviceAnnotations: {}
  credentialsName: 1password-connect-credentials
  credentialsKey: 1password-credentials.json
  imagePullPolicy: IfNotPresent
  version: "1.7.3"
  nodeSelector: {}
  probes:
    liveness: true
    readiness: true
  annotations: {}
  labels: {}
  podAnnotations: {}
  podLabels: {}
  tolerations: []
  dataVolume:
    name: shared-data
    type: emptyDir
    values: {}
  tls:
    enabled: false
  ingress:
    enabled: false
  profiler:
    enabled: false
    interval: 6h
    keepLast: 12
operator:
  create: true
  autoRestart: true
  applicationName: onepassword-connect-operator
  imagePullPolicy: IfNotPresent
  imageRepository: docker.io/1password/onepassword-operator
  pollingInterval: 600
  version: "1.8.1"
  nodeSelector: {}
  annotations: {}
  labels: {}
  podAnnotations: {}
  podLabels: {}
  tolerations: []
  watchNamespace:
    - vault
    - openshift-pipelines
    - openshift-devspaces
    - build
    - production
    - quality
  resources: {}
  token:
    name: onepassword-token
    key: token
  serviceAccount:
    create: true
    annotations: {}
    name: onepassword-connect-operator
  roleBinding:
    create: true
    name: onepassword-connect-operator
  clusterRole:
    create: true
    name: onepassword-connect-operator
  clusterRoleBinding:
    create: true
    name: onepassword-connect-operator
  logLevel: info
acceptanceTests:
  enabled: false
  fixtures: {}
