---
apiVersion: helm.openshift.io/v1beta1
kind: ProjectHelmChartRepository
metadata:
  name: 1password
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  connectionConfig:
    url: 'https://1password.github.io/connect-helm-charts'
  description: 1Password Connect Helm Charts
  name: 1password
