apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
  - operatorgroup.yaml
  - subscription.yaml
  - rolebinding.yaml
  - secrets.yaml
  - chains.yaml
  - chains-config.yaml
  - serviceaccount.yaml
  - ./eventlisteners
  - ./triggertemplates
  - ./pipelines
  - ./tasks
  - ./cron_builds
