---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: gitops-ssh-creds
  namespace: openshift-pipelines
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  itemPath: "vaults/ecjar5faqoioytl4l72rysn3fa/items/6btb3v5z22mguqtalmdciiikqa"
