---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: gitops-ssh-creds
  namespace: openshift-pipelines
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  itemPath: "vaults/Red Hat/items/[SSH] ahussey-redhat"
