---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: quality
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
  - crunchy-instance.yaml
  - db-init-sql.yaml
  - pgadmin.yaml
  - routes.yaml