---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../../../4-workloads/production
  - ../../../../4-workloads/quality
patches:
  - target:
      kind: ConsoleNotification
      name: classification-banner-top
    patch: |-
      - op: replace
        path: /spec/text
        value: 'Silent Auction Demo - ROSA'